FROM python:3.9.12-slim-buster

WORKDIR /usr/src/app

RUN apt-get update -y
RUN apt-get upgrade -y

RUN apt-get install -y git
RUN apt-get install -y python3-gmsh
RUN apt-get install -y g++


# Setup venv
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# RUN useradd -ms /bin/bash admin
# USER admin
# WORKDIR /home/user
# WORKDIR /usr/src/app

# COPY --chown=admin:admin requirements.txt ./
COPY requirements.txt ./
COPY requirements-deep.txt ./

# RUN pip install --user --upgrade pip
RUN pip install --upgrade pip
RUN pip install pytest
RUN pip install -r requirements.txt
RUN pip install torch==1.11
RUN pip install -r requirements-deep.txt

RUN rm requirements.txt
RUN rm requirements-deep.txt

ENV PYTHONPATH "${PYTHONPATH}:."
