TEST = False

NORMALIZE_ROTATE = True
############

TRAIN_SCALE = 1.0
VALIDATION_SCALE = 1.0
PRINT_SCALE = 1.0

FINAL_TIME = 2.0 if TEST else 8


MESH_DENSITY = 8 if TEST else 16
ADAPTIVE_TRAINING_MESH = False  #!# True

############

FORCES_RANDOM_SCALE = 1.3
U_RANDOM_SCALE = 0.2
V_RANDOM_SCALE = 2.5
OBSTACLE_ORIGIN_SCALE = 2.0 * TRAIN_SCALE

DATA_ZERO_FORCES = 0.5
DATA_ROTATE_VELOCITY = 0.5

U_NOISE_GAMMA = 0.1
U_IN_RANDOM_FACTOR = 0.005 * U_RANDOM_SCALE
V_IN_RANDOM_FACTOR = 0.005 * V_RANDOM_SCALE

############

DATA_FOLDER = f"{MESH_DENSITY}"
PRINT_DATA_CUTOFF = 0.1

############

VALIDATE_AT_EPOCHS = 1 if TEST else 20
DRAW_AT_MINUTES = 10 if TEST else 60
PRINT_SKIP = 0.1

L2_LOSS = False  #!#
BATCH_SIZE = 128  #!#
VALID_BATCH_SIZE = 128  #!#
SYNTHETIC_BATCHES_IN_EPOCH = 64 if TEST else 512  #!#
SYNTHETIC_SOLVERS_COUNT = BATCH_SIZE * SYNTHETIC_BATCHES_IN_EPOCH

############

DATALOADER_WORKERS = 4
GENERATION_WORKERS = 1 #2
GENERATION_MEMORY_LIMIT_GB = 24.0 / GENERATION_WORKERS
TOTAL_MEMORY_LIMIT_GB = 29.0

############

DROPOUT_RATE = 0.0  # 0.1  # 0.2  0.05
SKIP = True
# GRADIENT_CLIP = 10.0

ATTENTION_HEADS = None  # None 1 3 5

INITIAL_LR = 1e-4
LR_GAMMA = 1.0  # 0.999
FINAL_LR = 1e-6

LATENT_DIM = 128
ENC_LAYER_COUNT = 2
PROC_LAYER_COUNT = 0
DEC_LAYER_COUNT = 2
MESSAGE_PASSES = 8  # 5 # 10
