name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
      - name: Installing dependencies
        run: uv sync --group dev --python 3.11
      - name: Checking code quality
        run: |
          uv run black -l 100 -t py39 --diff --check $(git ls-files '*.py')
          PYTHONPATH=. uv run pylint --argument-rgx='[a-z_][a-z0-9_]{1,30}$|[xtUVW]' --attr-rgx='[a-z_][a-z0-9_]{1,30}$' --variable-rgx='[a-z_A][a-z0-9_]{0,30}|[UVWXYZ]$' --disable=missing-docstring --disable=too-few-public-methods --disable=duplicate-code --notes='FIXME,XXX,###' --max-args=8 --max-attributes=16 --max-public-methods=32 --max-locals=24 --max-attributes=16 conmech/
