name: Conmech Container Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: michaljur/conmech:latest
    steps:
      - name: Downloading code
        shell: bash
        run: |
          git init
          url=${{ github.repositoryUrl }}
          git remote add origin ${url/git:/https:}
          git pull origin ${{ github.sha }}
      - name: Install requirements
        shell: bash
        run: |
          pip install -r requirements.txt
      - name: Running tests
        shell: bash
        run: PYTHONPATH=. pytest --ignore=tests/test_deep_conmech -p no:unraisableexception -s
