name: Conmech Tests

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-14, windows-latest ]
        python-version: [ "3.9", "3.10", "3.11", "3.12" ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install pytest
      - run: pip install -r requirements.txt

      - if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get install -y python3-gmsh

      - run: PYTHONPATH=. pytest -p no:unraisableexception
