name: Conmech Tests

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-15-intel, windows-latest ]
        python-version: [ "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v3

      - run: uv sync --group dev --python ${{ matrix.python-version }}

      - if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get install -y python3-gmsh

      - run: PYTHONPATH=. uv run pytest -p no:unraisableexception
