name: Conmech Tests

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ 3.7, 3.8, 3.9 ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - run: python -m pip install --upgrade pip
      - run: pip install pytest pytest-env pytest-xdist

      - if: matrix.platform == 'windows-latest'
        run: pip install "jax[cpu]===0.3.22" -f https://whls.blob.core.windows.net/unstable/index.html --use-deprecated legacy-resolver
      
      - if: matrix.platform != 'windows-latest'
        run: pip install jaxlib==0.3.22

      - run: pip install -r requirements.txt

      - if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get install -y python3-gmsh

      - run: PYTHONPATH=. pytest --ignore=tests/test_deep_conmech -p no:unraisableexception
