name: Container Tests

on:
    push

jobs:
    run_tests:
        runs-on: ubuntu-18.04
        container:
            image: michaljur/conmech:latest
            credentials:
               username: michaljur
               password: ${{ secrets.DOCKER_HUB_TOKEN }}
        steps:
            - name: super-step
              shell: bash
              run: |
                echo "--This is running in my custom Docker image--"
                echo ${{ github.head_ref }}.${{ github.sha }}
                git init
                git remote add origin https://github.com/michalJur/conmech.git
                git pull origin 
                PYTHONPATH=. pytest --ignore=tests/test_deep_conmech -p no:unraisableexception
