name: Build Status

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.10

      - run: |
          pip install pytest
      - run: |
          pip install -r requirements.txt

      - if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get install -y python3-gmsh

      - run: PYTHONPATH=. pytest -p no:unraisableexception
