name: Deep Conmech Tests

defaults:
  run:
    shell: bash

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  run_deep_conmech_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - run: pip install pytest
      - run: pip install -r requirements.txt
      
      - run: pip install -r requirements-deep.txt

      - run: sudo apt-get install -y python3-gmsh

      - run: PYTHONPATH=. pytest tests/deep -p no:unraisableexception
